### ISSUE TITLE
Suggestion:  MapsPlus.kt

### ISSUE THREAD

**Issue by jlramirez** [SirWellington/alchemy-kotlin#1]
It would be nice to select a random entry from map. I'm new to Kotlin -- here's an attempt.

```
import java.util.Random
/**
 *  Select a random entry from map
 *
 * @return A key/value pair
 */
inline fun <reified K, reified V> MutableMap<K, V>.randomEntry(): MutableMap.MutableEntry<K, V>
{
    val mutableList = entries.toMutableList()
    val random = Random().nextInt(mutableList.size)

    return mutableList[random]
}
```

**Comment by SirWellington** [comment]
very nice. Feel free to open a pull-request

**Comment by SirWellington** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/843d8074-e7bc-409c-aeb1-2caf9f50dbf9-20e7579f-ea77-46b2-919c-3e91d7ab375a-v1.png?transparent=1&palette=1&width=246) 
Please make a pull request. Make sure that:

1. This is implemented as an extension variable
2. The extension is attached to a regular `Map`, and not a `Mutable` one
3. Delegate to the already-built `List.anyElement` variable
